### PR TITLE
Min image convention

### PR DESCRIPTION
**Pull request by tonimueller**

### CODE REVIEW

**Comment by MartinWenge** [comment]
Should the Power Of Two Box specialization check if the box sizes are valid?

**Comment by tonimueller** [comment]
There should be a check for the power of two and for the periodicity.

**Comment by MartinWenge** [comment]
The functions are only valid for full periodic boundaries now, should we split this for systems with mixed periodic boundaries?

**Comment by MartinWenge** [comment]
The current implementation seems to do the job. We could do some cleanup of the comments or take it as it is :)

**Pull request merged**
